site: eruimdas
title: Hasan Kemik
greetings: Hi there👋
description: This is Hasan and in this page(s) you'll find lots of things. Some are directly about me, some are just a way for me to share my knowledge.  Feel free to check them all!
lang: en-US
timezone:  Europe/Istanbul
repo: https://github.com/eruimdas/eruimdas.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: # replace with your disqus shortname

author:
  name: hasankemik
  bio: A minimal blog, where Hasan likes to write about anything ;)
  userpicture: https://res.cloudinary.com/eruimdas-github-io/image/upload/ar_1:1,b_rgb:262c35,bo_3px_solid_rgb:000000,c_fill,g_xy_center,q_100,r_max,w_1000,x_0,y_500/a_0/v1640899539/HasanKemik_a2w3sa.jpg
  username: eruimdas
  github: Eruimdas
  twitter: # twitter username
  email: hasan.kemikk@gmail.com

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://eruimdas.github.io" # Domain Name of host. [username].github.io for github pages
baseurl:  # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - vendor

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
